MOD-: Now uses whutil instead of whsys

diff --git a/whclamav/configure b/whclamav/configure
--- a/whclamav/configure
+++ b/whclamav/configure
@@ -17099,10 +17099,10 @@ WX_LIBS="`$WX_CONFIG --libs`"
 
 
 
-WH_CONFIGS="pkg-config libwhsystem-1.0"
-{ echo "$as_me:$LINENO: checking libwhsystem version" >&5
-echo $ECHO_N "checking libwhsystem version... $ECHO_C" >&6; }
-WH_CONFIG="pkg-config libwhsystem-1.0"
+WH_CONFIGS="pkg-config whutil-1.0"
+{ echo "$as_me:$LINENO: checking libwhutil version" >&5
+echo $ECHO_N "checking libwhutil version... $ECHO_C" >&6; }
+WH_CONFIG="pkg-config whutil-1.0"
 for VALUE in $WH_CONFIGS ; do
 	if WH_VERSION=`$VALUE --version 2>&1` ; then
 		WH_CONFIG=$VALUE
@@ -17115,14 +17115,14 @@ echo "${ECHO_T}$WH_VERSION" >&6; }
 else
 	{ echo "$as_me:$LINENO: result: not found" >&5
 echo "${ECHO_T}not found" >&6; }
-	{ { echo "$as_me:$LINENO: error: libwhsystem is required." >&5
-echo "$as_me: error: libwhsystem is required." >&2;}
+	{ { echo "$as_me:$LINENO: error: libwhutil is required." >&5
+echo "$as_me: error: libwhutil is required." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
-CPPFLAGS="$CPPFLAGS `$WH_CONFIG libwhsystem-1.0 --cflags`"
-CXXFLAGS="$CXXFLAGS `$WH_CONFIG libwhsystem-1.0 --cflags`"
-WH_LIBS="`$WH_CONFIG libwhsystem-1.0 --libs`"
+CPPFLAGS="$CPPFLAGS `$WH_CONFIG whutil-1.0 --cflags`"
+CXXFLAGS="$CXXFLAGS `$WH_CONFIG whutil-1.0 --cflags`"
+WH_LIBS="`$WH_CONFIG whutil-1.0 --libs`"
 
 
 
